#import "../model/diesn.typ": diesn-diagram, diesn-block-diagram, diesn-attention-diagram

= Diffusion Language Models in the Reservoir World <ch:diesn>

In this chapter, we present the architecture and operational principles of *DiESN* (_Diffusion Echo State Network_), the novel sequence modeling architecture developed in this thesis.  Specifically, we eliminate the computationally demanding, quadratic-complexity ($cal(O)(L^2)$) self-attention mechanism by replacing it with fixed, non-trainable recurrent layers inspired by Echo State Networks, instantiated through the *ParalESN* formulation. By combining these untrained diagonal recurrent reservoirs with lightweight local depthwise convolutions, modern adaptive normalizations, and an associative scan parallelization, DiESN achieves comprehensive bidirectional sequence mixing with sub-quadratic temporal scaling and a substantially reduced trainable parameter footprint.


== Model Architecture <sec:model_arch>

The overall organization of the DiESN architecture is illustrated in @fig:diesn_arch. The model processes continuous input sequences generated by the diffusion corruption process and is conditioned at every level on the current noise level (timestep).

A continuous sequence of soft-masked token representations and the scalar diffusion noise level $sigma_t$ are first mapped into the latent space by the token embedding and timestep embedder modules, respectively. The resulting sequence of embeddings $bold(u)^((0))$ is processed through a deep stack of $N$ identical DiESN blocks. Each block carries out global bidirectional sequence mixing and local feature refinement conditioned on the timestep vector $bold(c)$. 

Following the $N$ reservoir-based blocks, a single Flash Linear Attention layer performs a global cross-positional refinement step, after which an adaptive-layer-normalized linear readout head projects the hidden states to unnormalized vocabulary logits.

#figure(
  diesn-diagram,
  caption: [Overall architecture of the DiESN architecture. The continuous soft-masked input distributions $bold(x)_t$ and diffusion noise level $sigma_t$ are mapped by the token embeddings and timestep embedder into representations $bold(u)^((0))$ and conditioning vector $bold(c)$. The representations flow through a stack of $N$ DiESN blocks, a global Flash Linear Attention layer, and an AdaLN-modulated output projection to yield vocabulary logits.],
  placement: auto,
) <diesn_arch>

#figure(
  diesn-block-diagram,
  caption: [Detailed internal schematic of the DiESN Block. The conditioning vector $bold(c)$ modulates both sub-layers via an AdaLN-Zero linear projection producing scale, shift, and gate vectors. The first sub-layer performs bidirectional sequence mixing through parallel global (BiParalESN) and local (depthwise Conv1D) branches, fused additively and applied through a gated residual connection with dropout. The second sub-layer comprises a standard position-wise feed-forward network with GELU activation and gated residual addition.],
) <diesn_block>

==== Notation
Throughout this chapter, we index sequence positions by $i in {1, dots, L}$ and diffusion steps by $t$; $m in {1, dots, M}$ indexes the DiESN blocks. $d$ denotes the model width (hidden dimension), $N_h$ the reservoir size (number of hidden recurrent units), and $cal(V)$ denotes the vocabulary.

Trainable tensors and weight matrices are written in bold roman font ($bold(W), bold(b)$), whereas frozen, non-trainable reservoir tensors are explicitly designated with an overline ($overline(Lambda), overline(bold(W)), overline(bold(b))$). Element-wise (Hadamard) vector multiplication is denoted by $circle.small$.


== Input and Conditioning <sec:input_conditioning>

Following the soft-masked diffusion formulation introduced in @background (specifically @sm), the input at diffusion step $t$ is a sequence of continuous distributions $bold(x)_t^(1:L)$, with $bold(x)_t^i in Delta^(|cal(V)| - 1)$ rather than a discrete one-hot vector (only if soft masking is applied).

The embedding layer therefore acts as a continuous weighted lookup:
$ bold(u)_i^((0)) = bold(E)^top bold(x)_(t)^i in RR^d, quad bold(E) in RR^(|cal(V)| times d), $ <eq:soft_lookup>

which smoothly reduces to standard embedding lookup whenever $bold(x)_t^i$ is one-hot (i.e., for completely unmasked positions, as well as for masked positions when the soft-masking interpolation parameter $lambda = 0$).

The noise level $sigma_t$ is mapped to a conditioning vector $bold(c)$ by a dedicated timestep embedder:
$ bold(c) = bold(W)_2^("ts") phi(bold(W)_1^("ts") "SinEmb"(sigma_t)) in RR^d, $ <eq:timestep_embedder>

where $phi = "SiLU"$ and $"SinEmb"(dot)$ represents the canonical sinusoidal frequency encoding. Crucially, $bold(c)$ is a single vector shared across all sequence positions: conditioning enters the network exclusively through feature-wise adaptive modulation, never along the sequence axis. This keeps the effective sequence length unchanged and eliminates the quadratic overhead that would result from prepending conditioning tokens to self-attention contexts.


== The DiESN Block <sec:diesn_block>

The core computational unit of the architecture is the *DiESN Block*, depicted in @fig:diesn_block. Each block is conditioned through Adaptive Layer Normalization with zero initialization (*AdaLN-Zero*, Peebles & Xie, 2023 @peebles2023scalable). A single linear projection produces six modulation vectors from the timestep conditioning representation $bold(c)$:

$ [bold(gamma)_1, bold(beta)_1, bold(alpha)_1, bold(gamma)_2, bold(beta)_2, bold(alpha)_2] = bold(W)_("ada")^((m)) "SiLU"(bold(c)) + bold(b)_("ada")^((m)) in RR^(6d), $ <eq:adaln>

where $(bold(gamma)_1, bold(beta)_1)$ and $(bold(gamma)_2, bold(beta)_2)$ serve as the scale and shift modulation pairs for the two normalization stages, while $bold(alpha)_1, bold(alpha)_2 in RR^d$ act as residual gating vectors. The projection weights $bold(W)_("ada")^((m))$ and biases $bold(b)_("ada")^((m))$ are initialized to zero, ensuring that each DiESN block behaves as an identity transformation at the beginning of training, which significantly enhances numerical stability and gradient propagation in deep stacks.

=== Mixing Stage
Let $bold(u)^((m-1)) in RR^(L times d)$ denote the input to block $m$. The first sub-layer begins with adaptive pre-normalization:
$ bold(v)_i = "LN"(bold(u)_i^((m-1))) circle.small (bold(1) + bold(gamma)_1) + bold(beta)_1 . $ <eq:mod1>

The modulated representation $bold(v)$ is subsequently processed by two parallel complementary branches:
1. *Global branch (Bidirectional Linear Reservoir):* To capture long-range contextual dependencies across the entire sequence, the recurrence of ParalESN (see @paralesn) is executed independently in both forward and backward directions:
  $ arrow.r(bold(h))_i &= overline(Lambda)_(->)^((m)) arrow.r(bold(h))_(i-1) + tau(overline(bold(W))_(->)^((m)) bold(v)_i + overline(bold(b))_(->)^((m))), quad &arrow.r(bold(h))_0 = bold(0), \
    arrow.l(bold(h))_i &= overline(Lambda)_(<-)^((m)) arrow.l(bold(h))_(i+1) + tau(overline(bold(W))_(<-)^((m)) bold(v)_i + overline(bold(b))_(<-)^((m))), quad &arrow.l(bold(h))_(L+1) = bold(0), $ <eq:bidir>

  where $overline(Lambda)_(->)^((m)) = (1 - tau) I + tau Lambda_(->)^((m))$ and $overline(Lambda)_(<-)^((m)) = (1 - tau) I + tau Lambda_(<-)^((m))$ denote the effective diagonal transition matrices incorporating the leaky integration rate $tau in (0, 1]$, in accordance with the ParalESN formulation (Section 2.2.2).
  

  $arrow.r(bold(h))_i, arrow.l(bold(h))_i in CC^(N_h)$ represent the bidirectionality (forward and backward pass) of the model. Both directions are evaluated in parallel using the associative scan algorithm in $cal(O)(log L)$ parallel depth (see @paralesn).

  Bidirectionality is fundamentally indispensable in this setting: unlike autoregressive language modeling, where causal masking restricts attention to past tokens, text diffusion denoising is an inherently non-causal problem.

  The complex reservoir states from both directions are concatenated into a real-valued representation and projected back to the model dimension:
  $ bold(h)_i = [Re(arrow.r(bold(h))_i); Im(arrow.r(bold(h))_i); Re(arrow.l(bold(h))_i); Im(arrow.l(bold(h))_i)] in RR^(4 N_h), $ <eq:h_concat>
  $ bold(g)_i = bold(W)_("proj")^((m)) bold(h)_i, $ <eq:proj>

  where $bold(W)_("proj")^((m)) in RR^(d times 4 N_h)$ is a fixed projection matrix initialized using Kaiming uniform initialization @he2015delving and without bias. This matrix primarily serves to reduce the double dimensionality to $d$, resulting from the bidirectionality of ParalESN.

2. *Local branch (Depthwise Convolution):* In parallel with the reservoir, a local branch applies a depthwise 1-D convolution along the sequence axis with kernel size $k_c$, followed by a GELU @hendrycks2016gelu non-linearity:
  $ bold(ell)_i = phi_("gelu")((bold(W)_("conv")^((m)) * bold(v))_i + bold(b)_("conv")^((m))) . $ <eq:conv>

  This local branch captures and enriches the local context through interactions among adjacent tokens. Additionally, it constitutes the sole source of sequence-wise non-linearity in the mixing stage

The global and local representations are combined additively and passed through a gated residual connection with dropout:
$ bold(z)_i^((1)) = bold(g)_i + bold(ell)_i, $ <eq:z1>
$ bold(y)_i = bold(u)_i^((m-1)) + bold(alpha)_1 circle.small "Drop"(bold(z)_i^((1))) . $ <eq:res1>


=== Feed-Forward Stage
The second half of the DiESN block comprises a position-wise Multi-Layer Perceptron (FFN) modulated by the second set of AdaLN parameters:
$ bold(w)_i = "LN"(bold(y)_i) circle.small (bold(1) + bold(gamma)_2) + bold(beta)_2, $ <eq:mod2>
$ bold(z)_i^((2)) = bold(W)_2^((m)) phi_("gelu")(bold(W)_1^((m)) bold(w)_i + bold(b)_1^((m))) + bold(b)_2^((m)), $ <eq:ffn>
$ bold(u)_i^((m)) = bold(y)_i + bold(alpha)_2 circle.small "Drop"(bold(z)_i^((2))), $ <eq:res2>

where $bold(W)_1^((m)) in RR^(d_("ff") times d)$ and $bold(W)_2^((m)) in RR^(d times d_("ff"))$, with the intermediate hidden expansion dimension set to $d_("ff") = 4d$. The gated residual connection scales the FFN update by $bold(alpha)_2$, completing the block transformation. The MLP acts as our Readout as described in @paralesn. However, since the readout layer is optimized iteratively using backpropagation, closed-form methods (such as Ridge Regression) cannot be directly applied.


== Output Head <sec:output_head>

Following the stack of $M$ DiESN blocks, the sequence representation $bold(u)^((M))$ is refined globally before readout. A single Flash Linear Attention (Gated Linear Attention, GLA) @yang2023gated layer mixes representations globally across the sequence:
$ tilde(bold(u)) = "GLA"(bold(u)^((M))) . $ <eq:fla>

The output head then applies a final AdaLN modulation followed by an untied linear projection to the vocabulary space to produce the logits:
$ [bold(gamma)_f, bold(beta)_f] = bold(W)_("ada")^f "SiLU"(bold(c)) + bold(b)_("ada")^f, $ <eq:adaln_head>
$ bold(ell)_i^("logits") = bold(W)_("out") ("LN"(tilde(bold(u))_i) circle.small (bold(1) + bold(gamma)_f) + bold(beta)_f) + bold(b)_("out"), quad bold(W)_("out") in RR^(|cal(V)| times d) . $ <eq:logits>

The unnormalized logits $bold(ell)^("logits")$ are converted into predicted categorical probability distributions $bold(p)_(t-1)^(1:L)$ by a softmax operation. These probabilities are then routed to the unmasking and soft-masking modules described in @background (@mdlm and @sm), determining the sequence state for step $t-1$.


== Trainable and Frozen Parameters <sec:parameters>

A fundamental advantage of the DiESN architecture lies in its partitioning between trainable and frozen parameters, inheriting the training efficiency of the Reservoir Computing paradigm.

The set of frozen parameters is given by:
$ cal(P)_("frozen") = { overline(Lambda)_(->)^((m)), overline(Lambda)_(<-)^((m)), overline(bold(W))_(->)^((m)), overline(bold(W))_(<-)^((m)), overline(bold(b))_(->)^((m)), overline(bold(b))_(<-)^((m)), overline(W)_"proj" }_(m=1)^M . $

These recurrent transition matrices and input projections are sampled once at initialization in accordance with the ParalESN specification (see @paralesn) and remain completely fixed throughout all training iterations.

Because no gradients are accumulated for the recurrent parameters themselves, the backward pass never calculate the gradient nor does the optimizer allocate momentum and variance buffers for them. 

Furthermore, because the spectral condition $|overline(lambda)_j| < 1$ is enforced strictly at initialization and never perturbed by gradient updates, the *ESP* holds unconditionally throughout the entire training process. Consequently, DiESN guarantees internal dynamical stability without requiring eigenvalue clipping, spectral re-parameterization, or complex constrained optimization schemes.


== Training Objective <sec:training_objective>

The DiESN architecture is trained by minimizing the Negative Log-Likelihood (NLL) objective:

$ cal(L)(theta) = - EE_(t ~ U(0,1), bold(x)_0 ~ q_("data")(dot), bold(x)_t ~ q(dot | bold(x)_0)) [ 1/t sum_(i=1)^L bold(1)_(bold(x)_t^i = bold(m)) log ((bold(x)_0^i)^top g_theta (bold(x)_0^i | bold(x)_t^(1:L))) ] $ <eq:nll_loss>